#pragma once

// display section
#define CYD24

#define SPI_FREQUENCY 40000000
#define SPI_READ_FREQUENCY 16000000
#define TFT_MOSI ILI9341_SPI_BUS_MOSI_IO_NUM
#define TFT_MISO ILI9341_SPI_BUS_MISO_IO_NUM
#define TFT_SCLK ILI9341_SPI_BUS_SCLK_IO_NUM
#define TFT_CS ILI9341_SPI_CONFIG_CS_GPIO_NUM
#define TFT_DC ILI9341_SPI_CONFIG_DC_GPIO_NUM
#define TFT_RST ILI9341_DEV_CONFIG_RESET_GPIO_NUM
#define TFT_BUSY -1
#define TFT_BL GPIO_BCKL

#define TFT_WIDTH DISPLAY_WIDTH
#define TFT_HEIGHT DISPLAY_HEIGHT
#define FONT_SIZE 2
#define TFT_OFFSET_X 0
#define TFT_OFFSET_Y 0
#define TFT_OFFSET_ROTATION 1
#define SCREEN_ROTATE
#define SCREEN_TRANSITION_FRAMERATE 5

#define I2C_SDA CST816S_I2C_CONFIG_SDA_IO_NUM // I2C pins for this board
#define I2C_SCL CST816S_I2C_CONFIG_SCL_IO_NUM

// touch section
#define TOUCH_I2C_PORT 15
#define TOUCH_SLAVE_ADDRESS 0x5D
#define TOUCH_CS TF_CS
// #define TOUCH_RS    // TODO:Pinout
#define TOUCH_RESET CST816S_TOUCH_CONFIG_RST_GPIO_NUM
// #define TOUCH_SCK TF_SPI_SCK
// #define TOUCH_MOSI TF_SPI_MOSI
// #define TOUCH_MISO TF_SPI_MISO
#define TOUCH_BUSY -1
#define TOUCH_I2C_HOST CST816S_I2C_HOST
#define I2C_DEV_ADDRESS CST816S_IO_I2C_CONFIG_DEV_ADDRESS

#define HAS_TOUCHSCREEN 1
#define SCREEN_TOUCH_INT 16
#define SCREEN_TOUCH_USE_I2C

// LoRa Section
// module is a Reyax Rylr 933 lite
#define LORA_RX 35 // TODO: pinout
#define LORA_TX 22 // TODO: pinout
#define LORA_RESET 21
#define LORA_MOSI TFT_MOSI
#define LORA_MISO TFT_MISO
#define LORA_SCK TFT_SCLK
#define LORA_CS -1

// LED SECTION
// RGB LED configuration
#define RGBLED_RED RGB_LED_R
#define RGBLED_GREEN RGB_LED_G
#define RGBLED_BLUE RGB_LED_B
#define RGBLED_CA